version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
      - image: circleci/redis:4.0.12-alpine
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Run tests
          environment:
            REDIS_URL: redis://127.0.0.1:6379
          command: bundle exec rspec spec
